#Utilisation de la latest image nginx
FROM nginx:latest

#copier le fichier de conf dans le  repertoire nginx
COPY default.conf /etc/nginx/conf.d/default.conf

#exposer le port 80
#EXPOSE 80

#Démarrer Nginx
#CMD ["nginx", "-g", "deamon off;"]
